"""
🔴💀 Reporter — Assembles agent results into comprehensive Markdown reports
"""
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from loguru import logger

REPORT_TEMPLATE = """# 🔴💀 Red Team Report: Master Edition
**Session ID:** `{session_id}`
**Target:** `{target}`
**Risk Score:** `{risk_score}/10` {risk_emoji}
**Date:** {date}
**Operator:** Rick Jefferson / RJ Business Solutions

---

## Executive Summary (C-Suite Intelligence)
{summary}

---

## MITRE ATT&CK Matrix Heatmap
{mitre_heatmap}

---

## Subtask Execution Narrative
{subtask_table}

---

## Technical Findings & CVE Mapping
{findings}

---

## Knowledge & Tactical Intelligence
{knowledge}

---

## Persistence & Artifacts
{artifacts}

---

## Recommendations (Prioritized)
{recommendations}

---
*Generated by: 🔴💀 Ultimate Autonomous Red Team Arsenal v1.0 — Powered by Infermatic AI + Qwen-Thinking*
"""

class Reporter:
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def build_report(self, memory, model_router=None) -> str:
        data = memory.get_all()
        session_id = data.get("session_id", "unknown")
        target = data.get("context", {}).get("target", "Not specified")
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S CST")
        
        findings_list = data.get("findings", [])
        risk_score = min(10, len([f for f in findings_list if f.get("severity") in ["CRITICAL", "HIGH"]]) * 2.5)
        risk_emoji = "🔴" if risk_score > 7 else "🟡" if risk_score > 4 else "🟢"
        
        summary = self._generate_summary(data, model_router)
        mitre_heatmap = self._generate_mitre_heatmap(findings_list)
        subtask_table = self._format_subtask_table(data.get("subtasks", []))
        findings = self._format_findings(findings_list)
        knowledge = self._format_knowledge(data.get("knowledge", []))
        artifacts = self._format_artifacts(data.get("artifacts", []))
        recommendations = self._generate_recommendations(findings_list, model_router)
        
        report = REPORT_TEMPLATE.format(
            session_id=session_id, target=target, date=date, 
            risk_score=risk_score, risk_emoji=risk_emoji,
            summary=summary, mitre_heatmap=mitre_heatmap, 
            subtask_table=subtask_table, findings=findings, 
            knowledge=knowledge, artifacts=artifacts, 
            recommendations=recommendations
        )
        filename = self.output_dir / f"report_{session_id}_{int(time.time())}.md"
        filename.write_text(report)
        logger.info(f"[Reporter] Saved Legendary Report: {filename}")
        return report

    def _generate_mitre_heatmap(self, findings: List[Dict]) -> str:
        """Visualize ATT&CK techniques used in engagement."""
        techniques = {f.get("mitre_id", "T-Unknown") for f in findings if f.get("mitre_id")}
        if not techniques:
            return "_No specific ATT&CK techniques mapped._"
        return f"**Techniques Identified:** " + ", ".join([f"`{t}`" for t in techniques])

    def _generate_summary(self, data: Dict, model_router=None) -> str:
        if model_router:
            try:
                findings_text = "\n".join(f"- [{f.get('severity','?')}] {f.get('title','?')}: {f.get('description','')}" for f in data.get("findings", [])[:10])
                messages = [
                    {"role": "system", "content": "You are a senior red team lead. Write a professional C-Suite executive summary focusing on business impact and risk."},
                    {"role": "user", "content": findings_text or "No findings recorded."}
                ]
                return model_router.chat(messages, task_type="report_writing", temperature=0.5, max_tokens=1024)
            except Exception:
                pass
        findings = data.get("findings", [])
        return f"Autonomous red team assessment completed. {len(findings)} finding(s) identified. Immediate attention recommended for high-risk assets."

    def _generate_recommendations(self, findings: List[Dict], model_router=None) -> str:
        if not findings:
            return "No critical findings to remediate."
        if model_router:
            try:
                findings_text = "\n".join(f"- [{f.get('severity','?')}] {f.get('title','?')}: {f.get('description','')}" for f in findings[:10])
                messages = [{"role": "system", "content": "Provide numbered actionable remediation recommendations."}, {"role": "user", "content": findings_text}]
                return model_router.chat(messages, task_type="report_writing", temperature=0.3, max_tokens=1024)
            except Exception:
                pass
        return "\n".join(f"{i+1}. Remediate: {f.get('title','?')}" for i, f in enumerate(findings))

    def _format_subtask_table(self, subtasks: List[Dict]) -> str:
        if not subtasks:
            return "_No subtasks recorded._"
        rows = ["| # | Task | Type | Status |", "|---|------|------|--------|"]
        for st in subtasks:
            emoji = {"done": "✅", "error": "❌", "running": "🔄", "pending": "⏳"}.get(st.get("status", "?"), "❓")
            rows.append(f"| {st.get('id','')} | {st.get('title','')} | `{st.get('task_type','')}` | {emoji} {st.get('status','')} |")
        return "\n".join(rows)

    def _format_findings(self, findings: List[Dict]) -> str:
        if not findings:
            return "_No findings recorded._"
        sections = []
        for f in findings:
            sev = f.get("severity", "INFO")
            emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢", "INFO": "🔵"}.get(sev, "⚪")
            mitre = f"**MITRE ATT&CK:** `{f.get('mitre_id', 'N/A')}`" if f.get("mitre_id") else ""
            
            finding_text = f"### {emoji} [{sev}] {f.get('title', 'Untitled')}\n\n"
            finding_text += f"**Agent:** {f.get('agent', 'Unknown')}  \n"
            finding_text += f"{mitre}  \n" if mitre else ""
            finding_text += f"**Description:** {f.get('description', '')}  \n"
            finding_text += f"**Evidence:** `{f.get('evidence', 'N/A')[:200]}`"
            
            if f.get("remediation"):
                finding_text += f"\n\n{f.get('remediation')}"
                
            sections.append(finding_text)
        return "\n\n---\n\n".join(sections)

    def _format_knowledge(self, knowledge: List[Dict]) -> str:
        if not knowledge:
            return "_No knowledge items retrieved._"
        return "\n".join(f"- **{k.get('title', '?')}** ({k.get('source', '?')}) — {k.get('summary', '')[:100]}" for k in knowledge[:20])

    def _format_artifacts(self, artifacts: List[Dict]) -> str:
        if not artifacts:
            return "_No artifacts generated._"
        return "\n".join(f"- `{a.get('name', '?')}` ({a.get('type', 'file')}) → `{a.get('path', '?')}`" for a in artifacts)
