"""
🔴💀 Exploit Intelligence System — Collection Schemas
"""

CVE_INTELLIGENCE_SCHEMA = {
    "collection_name": "cve_intelligence",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "cve_id": "string",
        "title": "string",
        "description": "text",
        "published_date": "datetime",
        "last_modified": "datetime",
        "cvss_score": "float",
        "cvss_vector": "string",
        "severity": "string",
        "vulnerability_type": "list[string]",
        "vendor": "string",
        "product": "string",
        "affected_versions": "list[string]",
        "platform": "list[string]",
        "exploit_available": "boolean",
        "exploit_maturity": "string",
        "exploitdb_id": "string",
        "metasploit_module": "string",
        "github_pocs": "list[string]",
        "mitre_attack_techniques": "list[string]",
        "cwe_ids": "list[string]",
        "referenced_cves": "list[string]",
        "vendor_advisories": "list[string]",
        "exploited_in_wild": "boolean",
        "ransomware_campaigns": "list[string]",
        "apt_groups": "list[string]",
        "first_seen_exploited": "datetime",
        "detection_signatures": "list[string]",
        "yara_rules": "list[string]",
        "mitigation_steps": "text",
        "patch_available": "boolean",
        "success_rate": "float",
        "last_used": "datetime",
        "mission_count": "integer",
        "effectiveness_score": "float"
    }
}

EXPLOIT_TECHNIQUES_SCHEMA = {
    "collection_name": "exploit_techniques",
    "embedding_model": "microsoft/codebert-base",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "technique_id": "string",
        "name": "string",
        "description": "text",
        "category": "string",
        "attack_tactic": "list[string]",
        "attack_technique": "list[string]",
        "sub_techniques": "list[string]",
        "target_platform": "list[string]",
        "target_services": "list[string]",
        "prerequisites": "list[string]",
        "required_permissions": "string",
        "code_language": "list[string]",
        "payload_template": "text",
        "exploit_code": "text",
        "dependencies": "list[string]",
        "automation_level": "string",
        "tool_integration": "list[string]",
        "evasion_techniques": "list[string]",
        "obfuscation_methods": "list[string]",
        "success_rate": "float",
        "detection_rate": "float",
        "stealth_score": "float",
        "reliability_score": "float",
        "related_cves": "list[string]",
        "related_techniques": "list[string]",
        "successful_missions": "list[string]",
        "author": "string",
        "created_date": "datetime",
        "last_updated": "datetime",
        "use_count": "integer"
    }
}

MISSION_HISTORY_SCHEMA = {
    "collection_name": "mission_history",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "mission_id": "string",
        "mission_name": "string",
        "mission_type": "string",
        "objective": "text",
        "start_date": "datetime",
        "end_date": "datetime",
        "duration_hours": "float",
        "target_organization": "string",
        "target_industry": "string",
        "target_size": "string",
        "target_region": "string",
        "target_infrastructure": "list[string]",
        "kill_chain_phases": "list[string]",
        "techniques_used": "list[string]",
        "cves_exploited": "list[string]",
        "tools_used": "list[string]",
        "outcome": "string",
        "access_level_achieved": "string",
        "data_exfiltrated": "boolean",
        "persistence_established": "boolean",
        "lateral_movement_success": "boolean",
        "time_to_initial_access": "float",
        "time_to_domain_admin": "float",
        "systems_compromised": "integer",
        "flags_captured": "integer",
        "detection_events": "integer",
        "alerts_triggered": "integer",
        "ir_response": "boolean",
        "evasion_success_rate": "float",
        "what_worked": "text",
        "what_failed": "text",
        "innovations": "text",
        "recommendations": "text",
        "new_cves_discovered": "list[string]",
        "new_techniques_developed": "list[string]",
        "iocs_generated": "list[string]",
        "operator": "string",
        "team_size": "integer",
        "difficulty_rating": "float",
        "overall_score": "float"
    }
}

ATTACK_KNOWLEDGE_SCHEMA = {
    "collection_name": "attack_knowledge",
    "embedding_model": "jackaduma/SecBERT",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "attack_id": "string",
        "type": "string",
        "name": "string",
        "description": "text",
        "parent_tactic": "string",
        "parent_technique": "string",
        "child_techniques": "list[string]",
        "related_techniques": "list[string]",
        "platforms": "list[string]",
        "data_sources": "list[string]",
        "detection_methods": "list[string]",
        "used_by_groups": "list[string]",
        "used_by_software": "list[string]",
        "real_world_examples": "list[dict]",
        "available_tools": "list[string]",
        "available_exploits": "list[string]",
        "success_rate": "float",
        "usage_count": "integer",
        "detection_difficulty": "string",
        "mitigations": "list[string]",
        "detection_rules": "list[string]",
        "last_updated": "datetime",
        "version": "string"
    }
}

TARGET_INTELLIGENCE_SCHEMA = {
    "collection_name": "target_intelligence",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "target_id": "string",
        "organization_name": "string",
        "domain": "string",
        "industry": "string",
        "size": "string",
        "revenue": "string",
        "ip_ranges": "list[string]",
        "domains": "list[string]",
        "subdomains": "list[string]",
        "cloud_providers": "list[string]",
        "cdn_usage": "list[string]",
        "web_technologies": "list[string]",
        "frameworks": "list[string]",
        "cms_platforms": "list[string]",
        "programming_languages": "list[string]",
        "databases": "list[string]",
        "exposed_services": "list[dict]",
        "open_ports": "list[integer]",
        "ssl_certificates": "list[dict]",
        "email_servers": "list[string]",
        "nameservers": "list[string]",
        "known_cves": "list[string]",
        "misconfigurations": "list[string]",
        "outdated_software": "list[string]",
        "weak_services": "list[string]",
        "employees": "list[dict]",
        "key_personnel": "list[dict]",
        "leaked_credentials": "list[dict]",
        "phishing_targets": "list[string]",
        "security_tools": "list[string]",
        "security_vendors": "list[string]",
        "incident_history": "list[dict]",
        "bug_bounty_program": "boolean",
        "reconnaissance_notes": "text",
        "weaknesses": "text",
        "recommended_approaches": "text",
        "last_scanned": "datetime",
        "intelligence_quality": "string",
        "confidence_score": "float"
    }
}

IOC_DATABASE_SCHEMA = {
    "collection_name": "ioc_database",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "ioc_id": "string",
        "ioc_type": "string",
        "ioc_value": "string",
        "description": "text",
        "threat_type": "string",
        "malware_family": "string",
        "campaign": "string",
        "actor_group": "string",
        "first_seen": "datetime",
        "last_seen": "datetime",
        "confidence": "string",
        "severity": "string",
        "related_iocs": "list[string]",
        "related_cves": "list[string]",
        "related_missions": "list[string]",
        "related_attacks": "list[string]",
        "source": "list[string]",
        "tlp_level": "string",
        "tags": "list[string]",
        "used_in_operations": "boolean",
        "generated_by_arsenal": "boolean",
        "operation_ids": "list[string]",
        "added_date": "datetime",
        "expiration_date": "datetime",
        "active": "boolean"
    }
}

TOOL_ARSENAL_SCHEMA = {
    "collection_name": "tool_arsenal",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "tool_id": "string",
        "tool_name": "string",
        "category": "string",
        "description": "text",
        "primary_functions": "list[string]",
        "supported_platforms": "list[string]",
        "attack_techniques": "list[string]",
        "vulnerability_types": "list[string]",
        "language": "string",
        "dependencies": "list[string]",
        "installation_command": "text",
        "usage_examples": "text",
        "api_available": "boolean",
        "automation_support": "boolean",
        "framework_integration": "list[string]",
        "success_rate": "float",
        "detection_rate": "float",
        "reliability_score": "float",
        "usage_count": "integer",
        "stealth_level": "string",
        "signature_detection": "list[string]",
        "evasion_built_in": "boolean",
        "github_url": "string",
        "documentation_url": "string",
        "tutorial_urls": "list[string]",
        "version": "string",
        "last_updated": "datetime",
        "license": "string",
        "author": "string"
    }
}

ADVERSARY_PROFILES_SCHEMA = {
    "collection_name": "adversary_profiles",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "adversary_id": "string",
        "aliases": "list[string]",
        "attribution": "string",
        "type": "string",
        "tactics": "list[string]",
        "techniques": "list[string]",
        "procedures": "text",
        "target_industries": "list[string]",
        "target_regions": "list[string]",
        "target_types": "list[string]",
        "motivation": "list[string]",
        "tools_used": "list[string]",
        "malware_families": "list[string]",
        "custom_tools": "list[string]",
        "known_infrastructure": "list[string]",
        "c2_patterns": "text",
        "hosting_providers": "list[string]",
        "notable_campaigns": "list[dict]",
        "first_observed": "datetime",
        "last_activity": "datetime",
        "sophistication_level": "string",
        "resource_level": "string",
        "indicators": "list[string]",
        "mimicry_playbook": "text",
        "successful_defenses": "text",
        "last_updated": "datetime",
        "confidence": "string"
    }
}

PAYLOAD_LIBRARY_SCHEMA = {
    "collection_name": "payload_library",
    "embedding_model": "microsoft/codebert-base",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "payload_id": "string",
        "payload_name": "string",
        "payload_type": "string",
        "description": "text",
        "architecture": "list[string]",
        "platform": "list[string]",
        "language": "string",
        "size_bytes": "integer",
        "capabilities": "list[string]",
        "persistence_methods": "list[string]",
        "communication_protocol": "string",
        "encryption_used": "boolean",
        "payload_code": "text",
        "encoder_used": "string",
        "obfuscation_level": "string",
        "av_evasion": "list[string]",
        "sandbox_evasion": "boolean",
        "signature_hash": "string",
        "detected_by": "list[string]",
        "delivery_methods": "list[string]",
        "compatible_exploits": "list[string]",
        "c2_frameworks": "list[string]",
        "success_rate": "float",
        "detection_rate": "float",
        "reliability": "float",
        "mission_count": "integer",
        "created_date": "datetime",
        "last_modified": "datetime",
        "author": "string",
        "version": "string"
    }
}

OPSEC_PATTERNS_SCHEMA = {
    "collection_name": "opsec_patterns",
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "vector_dimension": 768,
    "distance_metric": "cosine",
    "metadata_schema": {
        "pattern_id": "string",
        "pattern_name": "string",
        "category": "string",
        "description": "text",
        "detection_method": "string",
        "detection_tools": "list[string]",
        "indicators": "list[string]",
        "alert_triggers": "list[string]",
        "evasion_methods": "list[string]",
        "implementation": "text",
        "effectiveness_score": "float",
        "complexity": "string",
        "applicable_phases": "list[string]",
        "applicable_techniques": "list[string]",
        "platform_specific": "list[string]",
        "used_by_adversaries": "list[string]",
        "mission_successes": "integer",
        "mission_failures": "integer",
        "bypass_rate": "float",
        "defender_countermeasures": "text",
        "adaptation_required": "boolean",
        "created_date": "datetime",
        "last_validated": "datetime",
        "reliability": "string"
    }
}

SCHEMAS = [
    CVE_INTELLIGENCE_SCHEMA, EXPLOIT_TECHNIQUES_SCHEMA, MISSION_HISTORY_SCHEMA,
    ATTACK_KNOWLEDGE_SCHEMA, TARGET_INTELLIGENCE_SCHEMA, IOC_DATABASE_SCHEMA,
    TOOL_ARSENAL_SCHEMA, ADVERSARY_PROFILES_SCHEMA, PAYLOAD_LIBRARY_SCHEMA,
    OPSEC_PATTERNS_SCHEMA
]
